//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Frendy.CRM.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Frendy.CRM.Resources.Properties.Resources.en", typeof(Resources_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action date.
        /// </summary>
        internal static string AUDIT_MODAL_ACTION_DATE {
            get {
                return ResourceManager.GetString("AUDIT_MODAL_ACTION_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action type.
        /// </summary>
        internal static string AUDIT_MODAL_ACTION_TYPE {
            get {
                return ResourceManager.GetString("AUDIT_MODAL_ACTION_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executor.
        /// </summary>
        internal static string AUDIT_MODAL_EXECUTOR {
            get {
                return ResourceManager.GetString("AUDIT_MODAL_EXECUTOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string AUDIT_MODAL_ID {
            get {
                return ResourceManager.GetString("AUDIT_MODAL_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string AUDIT_MODAL_TARGET {
            get {
                return ResourceManager.GetString("AUDIT_MODAL_TARGET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Information.
        /// </summary>
        internal static string AUDIT_MODAL_TITLE {
            get {
                return ResourceManager.GetString("AUDIT_MODAL_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string HEADER_ADMIN_ROLE {
            get {
                return ResourceManager.GetString("HEADER_ADMIN_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moderator.
        /// </summary>
        internal static string HEADER_MODER_ROLE {
            get {
                return ResourceManager.GetString("HEADER_MODER_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        internal static string HEADER_SUPPORT_ROLE {
            get {
                return ResourceManager.GetString("HEADER_SUPPORT_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string HEADER_USER_ROLE {
            get {
                return ResourceManager.GetString("HEADER_USER_ROLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audit log.
        /// </summary>
        internal static string NAV_AUDIT_LOG_TITLE {
            get {
                return ResourceManager.GetString("NAV_AUDIT_LOG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing staff.
        /// </summary>
        internal static string NAV_MANAGING_STAFF_TITLE {
            get {
                return ResourceManager.GetString("NAV_MANAGING_STAFF_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metrics.
        /// </summary>
        internal static string NAV_METRICS_TITLE {
            get {
                return ResourceManager.GetString("NAV_METRICS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User requests.
        /// </summary>
        internal static string NAV_USER_REQUESTS_TITLE {
            get {
                return ResourceManager.GetString("NAV_USER_REQUESTS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string NAV_USERS_TITLE {
            get {
                return ResourceManager.GetString("NAV_USERS_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copied to the clipboard!.
        /// </summary>
        internal static string NOTIFY_CLIPBOARD {
            get {
                return ResourceManager.GetString("NOTIFY_CLIPBOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action time.
        /// </summary>
        internal static string TABLE_ACTION_TIME_TITLE {
            get {
                return ResourceManager.GetString("TABLE_ACTION_TIME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string TABLE_ACTION_TITLE {
            get {
                return ResourceManager.GetString("TABLE_ACTION_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding new action.
        /// </summary>
        internal static string TABLE_ADD_NEW_ACTION {
            get {
                return ResourceManager.GetString("TABLE_ADD_NEW_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        internal static string TABLE_AUTHORIZATION_ACTION {
            get {
                return ResourceManager.GetString("TABLE_AUTHORIZATION_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocking the user.
        /// </summary>
        internal static string TABLE_BLOCKING_ACTION {
            get {
                return ResourceManager.GetString("TABLE_BLOCKING_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changing the user&apos;s role.
        /// </summary>
        internal static string TABLE_CHANGE_ROLE_ACTION {
            get {
                return ResourceManager.GetString("TABLE_CHANGE_ROLE_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting user list.
        /// </summary>
        internal static string TABLE_GET_USER_LIST_ACTION {
            get {
                return ResourceManager.GetString("TABLE_GET_USER_LIST_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        internal static string TABLE_ID_TITLE {
            get {
                return ResourceManager.GetString("TABLE_ID_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string TABLE_NAME_TITLE {
            get {
                return ResourceManager.GetString("TABLE_NAME_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately, the table is empty.
        /// </summary>
        internal static string TABLE_NO_DATA {
            get {
                return ResourceManager.GetString("TABLE_NO_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string TABLE_PAGINATION_NEXT {
            get {
                return ResourceManager.GetString("TABLE_PAGINATION_NEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string TABLE_PAGINATION_PREV {
            get {
                return ResourceManager.GetString("TABLE_PAGINATION_PREV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change.
        /// </summary>
        internal static string TABLE_PASS_CHANGE_ACTION {
            get {
                return ResourceManager.GetString("TABLE_PASS_CHANGE_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile update.
        /// </summary>
        internal static string TABLE_PROFILE_UPDATE_ACTION {
            get {
                return ResourceManager.GetString("TABLE_PROFILE_UPDATE_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string TABLE_REGISTRATION_ACTION {
            get {
                return ResourceManager.GetString("TABLE_REGISTRATION_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target.
        /// </summary>
        internal static string TABLE_TARGET_TITLE {
            get {
                return ResourceManager.GetString("TABLE_TARGET_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unblocking the user.
        /// </summary>
        internal static string TABLE_UNBLOCKING_ACTION {
            get {
                return ResourceManager.GetString("TABLE_UNBLOCKING_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action update.
        /// </summary>
        internal static string TABLE_UPDATE_ACTION {
            get {
                return ResourceManager.GetString("TABLE_UPDATE_ACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        internal static string TEXT_INPUT_SEARCH {
            get {
                return ResourceManager.GetString("TEXT_INPUT_SEARCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Profile.
        /// </summary>
        internal static string USER_MENU_GO_TO_PROFILE_TITLE {
            get {
                return ResourceManager.GetString("USER_MENU_GO_TO_PROFILE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string USER_MENU_LANG_TITLE {
            get {
                return ResourceManager.GetString("USER_MENU_LANG_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        internal static string USER_MENU_THEME_TITLE {
            get {
                return ResourceManager.GetString("USER_MENU_THEME_TITLE", resourceCulture);
            }
        }
    }
}
